CREATE TABLE dev_test.dim_dates (
	cal_id INT NOT NULL,
	cal_date NVARCHAR(10) NULL,
	cal_day NVARCHAR(10) NULL,
	cal_yrmth INT NULL,
	cal_qtr INT NULL,
	cal_mth INT NULL,
	cal_wkyr INT NULL,
	cal_dayyr INT NULL,
	cal_daymth INT NULL,
	cal_daywk INT NULL,
	mars_yrpd INT NULL,
	mars_qtr INT NULL,
	mars_pd INT NULL,
	mars_wkyr INT NULL,
	mars_wkpd INT NULL,
	mars_daypd INT NULL,
	mars_daywk INT NULL,
	mars_busdaypd INT NULL,
	mars_busdaywk INT NULL,
	mars_yrpdwk_desc NVARCHAR(255) NULL,
	mars_wk_seq INT NULL,
	mars_yrpd_desc NVARCHAR(255) NULL,
	first_daypd INT NULL,
	first_daywk INT NULL,
	sap_mars_yrpd INT NULL,
	cal_wk INT NULL,
	fiscal_yr_variant INT NULL,
	fiscal_yrpd INT NULL,
	posting_pd INT NULL,
	fiscal_yr INT NULL,
	CONSTRAINT PK_dim_dates PRIMARY KEY CLUSTERED (cal_id)
);